export type DummyTradeline = {
  id: string;
  bureau: 'Experian' | 'Equifax' | 'TransUnion';
  account_name: string;
  account_number_masked: string;
  account_type: string;
  status: string;
  balance_range_or_masked_balance: string;
  date_fields_synthetic: string;
  confidence_score: number;
  severity: 'Low' | 'Medium' | 'High' | 'Critical';
  possible_issue: string;
  issue_type:
    | 'bankruptcy'
    | 'medical_collection'
    | 'mortgage_late'
    | 'reaging'
    | 'charge_off'
    | 'duplicate_collection'
    | 'bureau_mismatch'
    | 'thin_file'
    | 'high_utilization'
    | 'identity_mismatch';
  recommended_letter_type: string;
};

export type DummyCreditReport = {
  id: string;
  login_email: string;
  display_name: string;
  persona: string;
  score_start: number;
  score_current: number;
  score_goal: number;
  bureau_scores: Record<'Experian' | 'Equifax' | 'TransUnion', number>;
  report_status: string;
  profile_summary: string;
  top_risk: string;
  stage: string;
  tradelines: DummyTradeline[];
  dispute_tests: string[];
  tracking_stages: string[];
  draft_letter_preview: string;
  email_preview: string;
};

export const dummyCreditReports: DummyCreditReport[] = [
  {
    id: 'cv-test-001',
    login_email: 'customer01@creditvivo.test',
    display_name: 'Jordan Brooks',
    persona: 'Bankruptcy recovery profile',
    score_start: 512,
    score_current: 548,
    score_goal: 680,
    bureau_scores: { Experian: 545, Equifax: 552, TransUnion: 547 },
    report_status: 'Chapter 7 public-record review',
    profile_summary: 'Synthetic consumer with discharged bankruptcy and several accounts that should be reviewed for included-in-bankruptcy reporting consistency.',
    top_risk: 'Bankruptcy-related tradelines may show inconsistent balances or statuses after discharge.',
    stage: 'Admin review required',
    tradelines: [
      {
        id: 'cv-test-001-tl-001',
        bureau: 'Experian',
        account_name: 'Metro Auto Finance',
        account_number_masked: '****1044',
        account_type: 'Auto loan',
        status: 'Included in bankruptcy',
        balance_range_or_masked_balance: '$0-$100',
        date_fields_synthetic: 'Discharge window synthetic 2023',
        confidence_score: 0.88,
        severity: 'High',
        possible_issue: 'Balance and discharge notation should match across bureaus.',
        issue_type: 'bankruptcy',
        recommended_letter_type: 'Bankruptcy reporting consistency review',
      },
      {
        id: 'cv-test-001-tl-002',
        bureau: 'TransUnion',
        account_name: 'First Premier Card',
        account_number_masked: '****7721',
        account_type: 'Credit card',
        status: 'Charge-off after bankruptcy window',
        balance_range_or_masked_balance: '$600-$800',
        date_fields_synthetic: 'Synthetic post-discharge review',
        confidence_score: 0.81,
        severity: 'High',
        possible_issue: 'Possible post-discharge balance/status inconsistency.',
        issue_type: 'bankruptcy',
        recommended_letter_type: 'Discharge status documentation request',
      },
    ],
    dispute_tests: ['bankruptcy status check', 'balance after discharge check', 'cross-bureau notation check'],
    tracking_stages: ['Draft created', 'Customer approval simulated', 'Admin review required', 'Compliance blocked', 'Not sent'],
    draft_letter_preview: 'DRAFT ONLY: Please investigate the bankruptcy-related reporting status and confirm the balance, status, and discharge notation for the listed synthetic accounts.',
    email_preview: 'Your bankruptcy-related review is ready. Credit Vivo found items that may need documentation review. No message was sent.',
  },
  {
    id: 'cv-test-002',
    login_email: 'customer02@creditvivo.test',
    display_name: 'Morgan Ellis',
    persona: 'Medical collection profile',
    score_start: 598,
    score_current: 611,
    score_goal: 700,
    bureau_scores: { Experian: 612, Equifax: 607, TransUnion: 614 },
    report_status: 'Medical collection review',
    profile_summary: 'Synthetic consumer with small medical collections, insurance-related ambiguity, and bureau coverage differences.',
    top_risk: 'Medical collections may need insurance/payment/evidence review before any dispute draft moves forward.',
    stage: 'Evidence checklist required',
    tradelines: [
      {
        id: 'cv-test-002-tl-001',
        bureau: 'Equifax',
        account_name: 'Regional Medical Collections',
        account_number_masked: '****2309',
        account_type: 'Medical collection',
        status: 'Collection account reported',
        balance_range_or_masked_balance: '$250-$350',
        date_fields_synthetic: 'Synthetic 2024 medical billing window',
        confidence_score: 0.91,
        severity: 'Medium',
        possible_issue: 'Insurance or billing documentation may affect next-step review.',
        issue_type: 'medical_collection',
        recommended_letter_type: 'Medical collection validation draft',
      },
      {
        id: 'cv-test-002-tl-002',
        bureau: 'TransUnion',
        account_name: 'County Radiology Billing',
        account_number_masked: '****9120',
        account_type: 'Medical collection',
        status: 'Paid collection',
        balance_range_or_masked_balance: '$0 reported',
        date_fields_synthetic: 'Synthetic paid-medical review',
        confidence_score: 0.84,
        severity: 'Medium',
        possible_issue: 'Paid status does not appear on all bureau records.',
        issue_type: 'medical_collection',
        recommended_letter_type: 'Paid medical reporting review',
      },
    ],
    dispute_tests: ['medical collection classification', 'paid status mismatch', 'evidence checklist'],
    tracking_stages: ['Evidence requested', 'Draft created', 'Customer approval simulated', 'Admin review required', 'Not sent'],
    draft_letter_preview: 'DRAFT ONLY: Please review the medical collection reporting, payment status, and documentation connected to the synthetic medical accounts.',
    email_preview: 'Credit Vivo found possible medical collection reporting issues. Upload/document review is still blocked in this test preview.',
  },
  {
    id: 'cv-test-003',
    login_email: 'customer03@creditvivo.test',
    display_name: 'Taylor Nguyen',
    persona: 'Mortgage late-payment profile',
    score_start: 643,
    score_current: 659,
    score_goal: 740,
    bureau_scores: { Experian: 661, Equifax: 655, TransUnion: 662 },
    report_status: 'Mortgage payment-history review',
    profile_summary: 'Synthetic mortgage account with a recent 30-day late on one bureau and clean history on others.',
    top_risk: 'A mortgage late can materially affect score blockers and needs high-confidence review.',
    stage: 'Payment evidence required',
    tradelines: [
      {
        id: 'cv-test-003-tl-001',
        bureau: 'Experian',
        account_name: 'Heritage Home Mortgage',
        account_number_masked: '****6670',
        account_type: 'Mortgage',
        status: '30 days late reported',
        balance_range_or_masked_balance: '$240k-$245k',
        date_fields_synthetic: 'Synthetic recent mortgage review',
        confidence_score: 0.87,
        severity: 'Critical',
        possible_issue: 'Payment-history notation differs from other bureaus.',
        issue_type: 'mortgage_late',
        recommended_letter_type: 'Mortgage payment-history investigation draft',
      },
    ],
    dispute_tests: ['mortgage late severity', 'payment-history mismatch', 'evidence requirement'],
    tracking_stages: ['Scanner found issue', 'Payment evidence needed', 'Draft blocked', 'Admin review required', 'Not sent'],
    draft_letter_preview: 'DRAFT ONLY: Please investigate the synthetic mortgage payment-history notation and compare it with payment evidence before any action.',
    email_preview: 'Your mortgage payment-history review needs evidence before Credit Vivo can prepare next steps. No email was sent.',
  },
  {
    id: 'cv-test-004',
    login_email: 'customer04@creditvivo.test',
    display_name: 'Casey Martin',
    persona: 'Collection re-aging profile',
    score_start: 571,
    score_current: 588,
    score_goal: 690,
    bureau_scores: { Experian: 590, Equifax: 581, TransUnion: 593 },
    report_status: 'Re-aging suspicion review',
    profile_summary: 'Synthetic old collection with recent activity/date changes that should trigger re-aging review logic.',
    top_risk: 'Date fields may make an old collection appear newer than expected.',
    stage: 'Compliance blocker active',
    tradelines: [
      {
        id: 'cv-test-004-tl-001',
        bureau: 'Equifax',
        account_name: 'Northstar Recovery Group',
        account_number_masked: '****4182',
        account_type: 'Collection',
        status: 'Collection updated recently',
        balance_range_or_masked_balance: '$900-$1,100',
        date_fields_synthetic: 'Original synthetic 2018 account; updated synthetic 2025 collection date',
        confidence_score: 0.78,
        severity: 'High',
        possible_issue: 'Possible re-aging signal because date fields were refreshed on an old collection.',
        issue_type: 'reaging',
        recommended_letter_type: 'Date reporting and validation review',
      },
    ],
    dispute_tests: ['re-aging detection', 'obsolete-date review', 'date-field mismatch'],
    tracking_stages: ['Scanner found issue', 'Compliance blocked', 'Admin review required', 'Evidence needed', 'Not sent'],
    draft_letter_preview: 'DRAFT ONLY: Please investigate the synthetic date fields and verify whether the collection reporting timeline is accurate and complete.',
    email_preview: 'Credit Vivo found a possible date-reporting issue. Review is draft-only and not sent.',
  },
  {
    id: 'cv-test-005',
    login_email: 'customer05@creditvivo.test',
    display_name: 'Avery Johnson',
    persona: 'Charge-off profile',
    score_start: 534,
    score_current: 549,
    score_goal: 665,
    bureau_scores: { Experian: 550, Equifax: 542, TransUnion: 555 },
    report_status: 'Charge-off balance/status review',
    profile_summary: 'Synthetic credit-card charge-off reporting with transferred/sold remarks and balance mismatch.',
    top_risk: 'Charge-off status and balance may not align across bureaus.',
    stage: 'Draft review',
    tradelines: [
      {
        id: 'cv-test-005-tl-001',
        bureau: 'TransUnion',
        account_name: 'Crescent Bankcard',
        account_number_masked: '****3951',
        account_type: 'Credit card',
        status: 'Charge-off transferred or sold',
        balance_range_or_masked_balance: '$1,800-$2,100',
        date_fields_synthetic: 'Synthetic 2021 charge-off review',
        confidence_score: 0.9,
        severity: 'High',
        possible_issue: 'Transferred/sold remark and balance reporting need consistency review.',
        issue_type: 'charge_off',
        recommended_letter_type: 'Charge-off balance/status investigation draft',
      },
    ],
    dispute_tests: ['charge-off classification', 'balance/status mismatch', 'original creditor check'],
    tracking_stages: ['Draft created', 'Customer approval simulated', 'Admin review required', 'Compliance review required', 'Not sent'],
    draft_letter_preview: 'DRAFT ONLY: Please investigate the charge-off balance, sold/transferred status, and original creditor details for the synthetic account.',
    email_preview: 'A charge-off review is ready in your Credit Vivo preview. This is not sent and results are not guaranteed.',
  },
  {
    id: 'cv-test-006',
    login_email: 'customer06@creditvivo.test',
    display_name: 'Riley Carter',
    persona: 'Duplicate collection profile',
    score_start: 557,
    score_current: 576,
    score_goal: 690,
    bureau_scores: { Experian: 570, Equifax: 579, TransUnion: 578 },
    report_status: 'Duplicate collection review',
    profile_summary: 'Synthetic profile where the same debt appears under two collection agencies.',
    top_risk: 'Duplicate reporting may inflate perceived negative-account count.',
    stage: 'Duplicate match review',
    tradelines: [
      {
        id: 'cv-test-006-tl-001',
        bureau: 'Experian',
        account_name: 'Atlas Collections',
        account_number_masked: '****1501',
        account_type: 'Collection',
        status: 'Collection account reported',
        balance_range_or_masked_balance: '$700-$800',
        date_fields_synthetic: 'Synthetic duplicate review window',
        confidence_score: 0.83,
        severity: 'High',
        possible_issue: 'Possible duplicate collection based on amount and original creditor pattern.',
        issue_type: 'duplicate_collection',
        recommended_letter_type: 'Duplicate collection review draft',
      },
      {
        id: 'cv-test-006-tl-002',
        bureau: 'Equifax',
        account_name: 'Summit Recovery Services',
        account_number_masked: '****1501',
        account_type: 'Collection',
        status: 'Collection account reported',
        balance_range_or_masked_balance: '$700-$800',
        date_fields_synthetic: 'Synthetic duplicate review window',
        confidence_score: 0.82,
        severity: 'High',
        possible_issue: 'Possible duplicate of Atlas Collections account.',
        issue_type: 'duplicate_collection',
        recommended_letter_type: 'Duplicate collection review draft',
      },
    ],
    dispute_tests: ['duplicate collection matching', 'same amount detection', 'bureau coverage grouping'],
    tracking_stages: ['Possible duplicate matched', 'Draft created', 'Customer approval simulated', 'Admin review required', 'Not sent'],
    draft_letter_preview: 'DRAFT ONLY: Please investigate whether the synthetic collection accounts represent the same alleged debt and whether reporting is accurate.',
    email_preview: 'Credit Vivo found possible duplicate collection reporting. No message was sent.',
  },
  {
    id: 'cv-test-007',
    login_email: 'customer07@creditvivo.test',
    display_name: 'Skyler Patel',
    persona: 'Bureau mismatch profile',
    score_start: 621,
    score_current: 633,
    score_goal: 720,
    bureau_scores: { Experian: 642, Equifax: 618, TransUnion: 639 },
    report_status: 'Cross-bureau mismatch review',
    profile_summary: 'Synthetic profile with a single account reporting different status and balance across bureaus.',
    top_risk: 'Cross-bureau inconsistency can drive customer confusion and admin review needs.',
    stage: '3-bureau comparison required',
    tradelines: [
      {
        id: 'cv-test-007-tl-001',
        bureau: 'Experian',
        account_name: 'Lakeview Personal Loan',
        account_number_masked: '****8088',
        account_type: 'Personal loan',
        status: 'Pays as agreed',
        balance_range_or_masked_balance: '$2,200-$2,400',
        date_fields_synthetic: 'Synthetic active account review',
        confidence_score: 0.89,
        severity: 'Medium',
        possible_issue: 'Experian shows positive status while Equifax shows delinquency.',
        issue_type: 'bureau_mismatch',
        recommended_letter_type: 'Cross-bureau consistency review',
      },
      {
        id: 'cv-test-007-tl-002',
        bureau: 'Equifax',
        account_name: 'Lakeview Personal Loan',
        account_number_masked: '****8088',
        account_type: 'Personal loan',
        status: '60 days late reported',
        balance_range_or_masked_balance: '$2,900-$3,100',
        date_fields_synthetic: 'Synthetic active account review',
        confidence_score: 0.86,
        severity: 'High',
        possible_issue: 'Equifax status and balance differ from other bureaus.',
        issue_type: 'bureau_mismatch',
        recommended_letter_type: 'Cross-bureau consistency review',
      },
    ],
    dispute_tests: ['3-bureau mismatch', 'wrong balance', 'wrong status'],
    tracking_stages: ['Bureau mismatch found', 'Draft created', 'Admin review required', 'Compliance review required', 'Not sent'],
    draft_letter_preview: 'DRAFT ONLY: Please compare the synthetic account status and balance across bureaus and investigate any incomplete or inaccurate reporting.',
    email_preview: 'Your 3-bureau comparison is ready for review. No email was sent.',
  },
  {
    id: 'cv-test-008',
    login_email: 'customer08@creditvivo.test',
    display_name: 'Jamie Wilson',
    persona: 'Thin-file profile',
    score_start: 682,
    score_current: 688,
    score_goal: 735,
    bureau_scores: { Experian: 690, Equifax: 681, TransUnion: 693 },
    report_status: 'Thin-file education review',
    profile_summary: 'Synthetic consumer with limited tradelines, few negatives, and score-growth opportunities mostly tied to depth/utilization.',
    top_risk: 'Few accounts make score less resilient; dispute strategy may not be the primary next step.',
    stage: 'Education and score-path review',
    tradelines: [
      {
        id: 'cv-test-008-tl-001',
        bureau: 'Experian',
        account_name: 'Starter Bank Card',
        account_number_masked: '****5107',
        account_type: 'Credit card',
        status: 'Pays as agreed',
        balance_range_or_masked_balance: '$90-$140',
        date_fields_synthetic: 'Synthetic new-file review',
        confidence_score: 0.93,
        severity: 'Low',
        possible_issue: 'Thin-file profile; not a dispute-heavy case.',
        issue_type: 'thin_file',
        recommended_letter_type: 'No dispute draft recommended',
      },
    ],
    dispute_tests: ['thin file detection', 'no-dispute recommendation', 'education path'],
    tracking_stages: ['Review complete', 'Education path shown', 'No dispute draft recommended', 'Admin review optional', 'Not sent'],
    draft_letter_preview: 'DRAFT ONLY: No dispute letter is recommended from this synthetic thin-file profile without a clear report error.',
    email_preview: 'Your Credit Vivo preview shows score-building guidance rather than dispute prep. No email was sent.',
  },
  {
    id: 'cv-test-009',
    login_email: 'customer09@creditvivo.test',
    display_name: 'Drew Simmons',
    persona: 'High-utilization profile',
    score_start: 604,
    score_current: 617,
    score_goal: 710,
    bureau_scores: { Experian: 616, Equifax: 611, TransUnion: 624 },
    report_status: 'Utilization blocker review',
    profile_summary: 'Synthetic consumer with high revolving utilization and one minor derogatory item.',
    top_risk: 'Score impact is likely utilization-heavy, so next best action should not be dispute-only.',
    stage: 'Score blocker review',
    tradelines: [
      {
        id: 'cv-test-009-tl-001',
        bureau: 'TransUnion',
        account_name: 'Everyday Rewards Card',
        account_number_masked: '****7214',
        account_type: 'Credit card',
        status: 'Open / high utilization',
        balance_range_or_masked_balance: '$4,700-$4,900 of $5,000 limit',
        date_fields_synthetic: 'Synthetic current-cycle review',
        confidence_score: 0.94,
        severity: 'High',
        possible_issue: 'High utilization is a score blocker but not necessarily a report error.',
        issue_type: 'high_utilization',
        recommended_letter_type: 'No dispute draft; utilization action recommended',
      },
    ],
    dispute_tests: ['utilization scoring', 'next-best-action routing', 'no guarantee language'],
    tracking_stages: ['Score blocker found', 'Utilization action recommended', 'No letter sent', 'Progress tracked', 'Not sent'],
    draft_letter_preview: 'DRAFT ONLY: No dispute letter is recommended for accurate high utilization; customer action plan is shown instead.',
    email_preview: 'Your preview shows high utilization as a possible score blocker. No score increase is guaranteed and no email was sent.',
  },
  {
    id: 'cv-test-010',
    login_email: 'customer10@creditvivo.test',
    display_name: 'Alex Rivera',
    persona: 'Identity mismatch profile',
    score_start: 586,
    score_current: 602,
    score_goal: 700,
    bureau_scores: { Experian: 606, Equifax: 595, TransUnion: 605 },
    report_status: 'Personal information mismatch review',
    profile_summary: 'Synthetic consumer with mixed name/address signals and unfamiliar inquiry/account indicators.',
    top_risk: 'Identity mismatch should route to evidence and admin review before disputes or escalation.',
    stage: 'Identity evidence required',
    tradelines: [
      {
        id: 'cv-test-010-tl-001',
        bureau: 'Equifax',
        account_name: 'Unknown Retail Card',
        account_number_masked: '****0092',
        account_type: 'Retail card',
        status: 'Account not recognized by consumer',
        balance_range_or_masked_balance: '$300-$500',
        date_fields_synthetic: 'Synthetic unfamiliar-account review',
        confidence_score: 0.76,
        severity: 'Critical',
        possible_issue: 'Unrecognized account and identity-data mismatch require document review.',
        issue_type: 'identity_mismatch',
        recommended_letter_type: 'Identity-related account investigation draft',
      },
    ],
    dispute_tests: ['identity mismatch routing', 'unrecognized account', 'evidence before escalation'],
    tracking_stages: ['Identity mismatch found', 'Evidence required', 'Draft blocked', 'Admin review required', 'Not sent'],
    draft_letter_preview: 'DRAFT ONLY: Please investigate the synthetic unrecognized account after identity evidence and admin review are complete.',
    email_preview: 'Credit Vivo found identity-related items that require careful review. No email was sent.',
  },
];

export const dummyReportById = Object.fromEntries(dummyCreditReports.map((report) => [report.id, report])) as Record<string, DummyCreditReport>;

export function getDummyReport(reportId?: string | null) {
  if (reportId && dummyReportById[reportId]) return dummyReportById[reportId];
  return dummyCreditReports[0];
}

export const dummyReportCoverage = [
  'bankruptcy',
  'medical_collection',
  'mortgage_late',
  'reaging',
  'charge_off',
  'duplicate_collection',
  'bureau_mismatch',
  'thin_file',
  'high_utilization',
  'identity_mismatch',
] as const;
