export const learningTopics = [
  {
    id: "free-weekly-reports",
    title: "Use Your Free Weekly Reports With Credit Vivo",
    category: "Free weekly reports",
    duration: 180,
    format: "learning_video",
    hook: "Your credit report can change. Credit Vivo helps you track what changed.",
    keyPoints: ["Customers can review updated reports regularly", "All three bureaus may report differently", "Upload reports to refresh the scan", "Credit Vivo compares changes over time"],
    cta: "Upload your latest reports and refresh your scan.",
  },
  {
    id: "three-bureau-comparison",
    title: "Why Your 3 Credit Reports Can Be Different",
    category: "3-bureau comparison",
    duration: 180,
    format: "learning_video",
    hook: "Equifax, Experian, and TransUnion do not always match.",
    keyPoints: ["Different bureaus may show different balances", "Account status can vary", "Dates and timelines may need review", "Credit Vivo compares the differences"],
    cta: "Compare your reports with Credit Vivo.",
  },
  {
    id: "negative-account-review",
    title: "Why Negative Accounts Need Careful Review",
    category: "Negative account review",
    duration: 180,
    format: "learning_video",
    hook: "Collections and charge-offs need more than a quick glance.",
    keyPoints: ["Review balance", "Review status", "Review Date of First Delinquency", "Review original creditor", "Review timeline"],
    cta: "Review your negative accounts.",
  },
  {
    id: "dispute-packet",
    title: "What Goes Inside a Strong Dispute Packet",
    category: "Dispute packet basics",
    duration: 180,
    format: "learning_video",
    hook: "A strong dispute is more than a letter.",
    keyPoints: ["Cover letter", "3-bureau comparison", "Relevant credit report pages", "Evidence", "ID and proof of address when needed", "Mail tracking"],
    cta: "Review and approve your packet.",
  },
  {
    id: "credit-improvement-process",
    title: "Credit Improvement Is a Process",
    category: "Credit improvement timeline",
    duration: 180,
    format: "learning_video",
    hook: "Credit improvement is a process, not a one-click fix.",
    keyPoints: ["Dispute rounds can take time", "Responses must be reviewed", "Verified does not always mean resolved", "Follow-ups may be needed", "Progress should be tracked"],
    cta: "Follow your Credit Vivo plan.",
  },
];
